import { supabase } from './supabase-client.js';
import { IS_CONFIGURED } from './config.js';
import { header,setStatus,calculateExperience,toast } from './common.js?v=20260708f';
header();
const loginView=document.querySelector('#loginView'),profileView=document.querySelector('#profileView'),loginForm=document.querySelector('#inlineLoginForm'),profileForm=document.querySelector('#inlineProfileForm'),loginStatus=document.querySelector('#loginStatus'),profileStatus=document.querySelector('#profileStatus');let user=null,profile={};
function showLogin(){loginView.hidden=false;profileView.hidden=true;document.querySelectorAll('[data-auth]').forEach(x=>x.hidden=true);document.querySelectorAll('[data-guest]').forEach(x=>x.hidden=false)}
async function showProfile(u){user=u;loginView.hidden=true;profileView.hidden=false;document.querySelectorAll('[data-auth]').forEach(x=>x.hidden=false);document.querySelectorAll('[data-guest]').forEach(x=>x.hidden=true);const {data,error}=await supabase.from('pilotes').select('*').eq('id',user.id).maybeSingle();if(error)return setStatus(profileStatus,error.message,'error');profile=data||{};if(!data){profileForm.prenom.value=user.user_metadata?.prenom||'';profileForm.nom.value=user.user_metadata?.nom||''}Object.entries(profile).forEach(([k,v])=>{const input=profileForm.elements[k];if(input&&input.type!=='checkbox'&&input.type!=='file')input.value=v??''});profileForm.gz_requested.checked=!!profile.gz_requested;document.querySelector('#avatarPreview').src=profile.photo_url||'assets/logo-frd.jpeg';document.querySelector('#experiencePreview').textContent=calculateExperience(profile.date_debut_rc_drift);if(data&&!profile.paddock_approved)setStatus(profileStatus,'Ta carte attend la validation d’un administrateur.')}
loginForm.addEventListener('submit',async e=>{e.preventDefault();if(!IS_CONFIGURED)return setStatus(loginStatus,'Supabase n’est pas configuré.','error');loginForm.classList.add('loading');try{const {data,error}=await supabase.auth.signInWithPassword({email:loginForm.email.value,password:loginForm.password.value});if(error)throw error;if(!data.user)throw new Error('Connexion impossible.');await showProfile(data.user)}catch(error){setStatus(loginStatus,error.message,'error')}finally{loginForm.classList.remove('loading')}});
async function upload(name,prefix,urlField,pathField){const file=profileForm.elements[name].files[0];if(!file)return {[urlField]:profile[urlField]||null,[pathField]:profile[pathField]||null};if(file.size>3145728)throw new Error('Chaque photo doit faire moins de 3 Mo.');const ext=file.name.split('.').pop().toLowerCase(),path=`${user.id}/${prefix}.${ext}`;const {error}=await supabase.storage.from('avatars').upload(path,file,{upsert:true,contentType:file.type});if(error)throw error;return {[urlField]:supabase.storage.from('avatars').getPublicUrl(path).data.publicUrl,[pathField]:path}}
profileForm.date_debut_rc_drift.addEventListener('change',()=>document.querySelector('#experiencePreview').textContent=calculateExperience(profileForm.date_debut_rc_drift.value));
profileForm.addEventListener('submit',async e=>{e.preventDefault();profileForm.classList.add('loading');try{const images=Object.assign({},await upload('photo','pilote','photo_url','photo_path'),await upload('photo_carrosserie','carrosserie','carrosserie_url','carrosserie_path'),await upload('photo_chassis','chassis','chassis_url','chassis_path'));const fields=['nom','prenom','pseudo','chassis','moteur','esc','servo','gyro','radio','batterie','pneus','carrosserie','date_debut_rc_drift','style_pilotage','objectifs'];const payload=Object.fromEntries(fields.map(k=>[k,profileForm.elements[k].value.trim()||null]));Object.assign(payload,images,{gz_requested:profileForm.gz_requested.checked});const {data,error}=await supabase.from('pilotes').update(payload).eq('id',user.id).select().single();if(error)throw error;profile=data;document.querySelector('#avatarPreview').src=profile.photo_url||'assets/logo-frd.jpeg';setStatus(profileStatus,'Profil enregistré. Il sera visible après validation par un administrateur.','success');toast('Profil mis à jour')}catch(error){setStatus(profileStatus,error.message,'error')}finally{profileForm.classList.remove('loading')}});
document.querySelector('#inlineLogout').addEventListener('click',async()=>{await supabase.auth.signOut();user=null;profile={};loginForm.reset();showLogin()});
const {data:{session}}=await supabase.auth.getSession();session?.user?await showProfile(session.user):showLogin();
