import { supabase } from './supabase-client.js';import { initShell,setupNotice,calculateExperience,setStatus,toast,esc } from './common.js?v=20260708e';
const demos={
 'demo-1':{pseudo:'Sideways',nom:'Martin',prenom:'Alex',chassis:'Reve D RDX',moteur:'10.5T Brushless',esc:'Hobbywing XD10',servo:'Reve D RS-ST',gyro:'Yokomo DP-302 V4',radio:'Sanwa MT-5',batterie:'Shorty 2S 4000 mAh',pneus:'DS Racing LF-5',carrosserie:'Nissan Silvia S15',date_debut_rc_drift:'2020-06-01',style_pilotage:'Rapide, précis, avec beaucoup d’angle et des transitions engagées.',objectifs:'Progresser en tandem et représenter FRD sur les événements nationaux.',gz_approved:true,photo_url:'assets/logo-frd.jpeg'},
 'demo-2':{pseudo:'LeoSlide',nom:'Durand',prenom:'Léo',chassis:'Yokomo RD 2.0',moteur:'10.5T',esc:'BL-PRO4',servo:'SP-03D V2',gyro:'YG-302 V2',radio:'Futaba T4PM',batterie:'LiPo 2S',pneus:'Yokomo DRC',carrosserie:'Toyota GR86',date_debut_rc_drift:'2023-03-15',style_pilotage:'Fluide et propre, priorité aux belles trajectoires.',objectifs:'Développer les tandems et participer à une compétition.',gz_approved:false,photo_url:'assets/logo-frd.jpeg'},
 'demo-3':{pseudo:'Yellow Line',nom:'Rossi',prenom:'Nina',chassis:'MST RMX 2.5',moteur:'13.5T',esc:'Hobbywing XR10',servo:'Reve D',gyro:'MST MGX',radio:'Sanwa',batterie:'Shorty 2S',pneus:'DS Racing',carrosserie:'BMW E30',date_debut_rc_drift:'2022-09-01',style_pilotage:'Technique et agressif, proche des clips.',objectifs:'Multiplier les rencontres et faire découvrir le RC Drift.',gz_approved:true,photo_url:'assets/logo-frd.jpeg'}
};
await initShell();setupNotice(document.querySelector('.driver-page'));const id=new URLSearchParams(location.search).get('id');let p=demos[id];if(supabase&&id&&!id.startsWith('demo-')){const {data,error}=await supabase.from('pilotes').select('*').eq('id',id).single();if(error)setStatus(document.querySelector('#status'),'Pilote introuvable.','error');else p=data}if(!p)p=demos['demo-1'];
const set=(id,value,fallback='À compléter')=>document.querySelector(`#${id}`).textContent=esc(value)||fallback;set('pilotPseudo',p.pseudo,'PILOTE FRD');set('pilotIdentity',`${esc(p.prenom)} ${esc(p.nom)}`);set('pilotExperience',calculateExperience(p.date_debut_rc_drift));set('pilotStyle',p.style_pilotage);set('pilotGoals',p.objectifs);document.querySelector('#pilotGz').hidden=!p.gz_approved;
function replaceMedia(id,url,label){if(!url)return;const old=document.querySelector(`#${id}`),img=document.createElement('img');img.id=id;img.className=old.className.replace('media-fallback','');img.src=url;img.alt=label;img.crossOrigin='anonymous';old.replaceWith(img)}replaceMedia('pilotMainPhoto',p.photo_url,'Photo pilote');replaceMedia('pilotCarPhoto',p.carrosserie_url,'Carrosserie RC');replaceMedia('chassisPhoto',p.chassis_url,'Châssis RC');
const specs=[['Châssis',p.chassis],['Moteur',p.moteur],['ESC',p.esc],['Servo',p.servo],['Gyro',p.gyro],['Radio',p.radio],['Batterie',p.batterie],['Pneus',p.pneus],['Carrosserie',p.carrosserie]];const grid=document.querySelector('#setupGrid');specs.forEach(([label,value])=>{const d=document.createElement('div');const s=document.createElement('span'),b=document.createElement('strong');s.textContent=label;b.textContent=esc(value)||'—';d.append(s,b);grid.append(d)});
document.querySelector('#sharePilot').onclick=async()=>{const data={title:`${p.pseudo||p.prenom} • Pilote FRD`,text:`Découvre la fiche de ${p.pseudo||p.prenom}, pilote FRD.`,url:location.href};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);toast('Lien copié')}}catch(e){if(e.name!=='AbortError')toast('Partage indisponible')}};
async function ensureExporter(){if(typeof window.html2canvas==='function')return window.html2canvas;return new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://unpkg.com/html2canvas@1.4.1/dist/html2canvas.min.js';script.onload=()=>resolve(window.html2canvas);script.onerror=()=>reject(new Error('Module image indisponible'));document.head.append(script)})}
document.querySelector('#downloadPilot').onclick=async()=>{const button=document.querySelector('#downloadPilot');button.disabled=true;button.textContent='Création…';try{const exporter=await ensureExporter();const canvas=await exporter(document.querySelector('#driverPoster'),{backgroundColor:'#080808',scale:2,useCORS:true,logging:false});const a=document.createElement('a');a.download=`FRD-${(p.pseudo||p.prenom||'pilote').replace(/[^a-z0-9]/gi,'-')}.png`;a.href=canvas.toDataURL('image/png');a.click();toast('Fiche PNG créée')}catch(e){toast('Impossible de créer l’image')}finally{button.disabled=false;button.textContent='Télécharger en PNG'}};
